Repository tuntunkun-org/noct, pull requests merged in 2020-05, with the labels that each got.

#18 [ドキュメント作成] SLACKの利用方法追記
  Pipfile
  Pipfile.lock
  README.md
  docs/common/project.md
  docs/index.md
  docs/slack/images/enable_incoming_webhook_1.jpeg
  docs/slack/images/slack_command_example.jpeg
  docs/slack/images/slack_notification_url.png
  docs/slack/images/slack_single_button.png
  docs/slack/index.md
  docs/theme/highlight.css
  mkdocs.yml
  setup.py
Labels: ドキュメント

#19 [Feature 10] Pipenv を Poetryにマイグレ
  Pipfile
  Pipfile.lock
  poetry.lock
  pyproject.toml
  setup.py
Labels: 改善

#20 [Feature 11] ライセンスの記載を追記
  LICENSE
  pyproject.toml
Labels: ドキュメント

#26 [設定変更] 1.0.4
  README.md
  noct/cli.py
  pyproject.toml
Labels: 改善

#25 Implement test codes to wipe out fake test code
  poetry.lock
  pyproject.toml
  tests/test_noct.py
  tests/test_ok.py
  tests/test_slack.py
Labels: テスト
