Repository tuntunkun-org/noct, pull requests merged in 2020-04, with the labels that each got.

#3 add editorconfig
  .editorconfig
Labels: improve

#4 [Feature 2] SLACK通知コマンドの実装
  Pipfile
  Pipfile.lock
  main.py
  noct/__init__.py
  noct/cli.py
  noct/schema/__init__.py
  noct/schema/attachment/__init__.py
  noct/schema/attachment/action.py
  noct/schema/attachment/attachment.py
  noct/schema/block/__init__.py
  noct/schema/block/divider.py
  noct/schema/block/field.py
  noct/schema/block/plain_text.py
  noct/schema/block/section.py
  noct/schema/slack.py
  setup.py
Labels: enhancement

#6 メッセンジャー種別を切り替えるためのコマンド追加
  noct/cli.py
Labels: improve

#8 ドキュメントの追記
  Pipfile
  Pipfile.lock
  docs/index.md
  docs/slack/index.md
  mkdocs.yml
Labels: documentation

#11 [Feature 6] 短いコマンドオプションの廃止
  noct/cli.py
Labels: 改善

#14 Fix #13 slack サブコマンドの `--buttons` オプションの不正な引数に対応
  noct/cli.py
Labels: バグ

#16 [Docs 2] SLACK通知コマンドのドキュメント追加
  Pipfile
  Pipfile.lock
  docs/slack/index.md
  docs/src/_snippets/abbr.txt
  docs/src/_snippets/critic-accept-example.txt
  docs/src/_snippets/critic-preview-example.txt
  docs/src/_snippets/links.txt
  docs/src/_snippets/mathjax.txt
  docs/src/_snippets/refs.txt
  docs/src/_snippets/uml.txt
  docs/theme/extra-0d9305e748.js
  docs/theme/extra-174a536342.css
  docs/theme/extra-424d7dfff1.css
  mkdocs.yml
Labels: ドキュメント
